---

apiVersion: v1
kind: Pod
metadata:
  name: couchdb
spec:
  containers:
  - name: couchdb
    image: bitnami/couchdb:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: COUCHDB_USER
      value: "admin"
    - name: COUCHDB_PASSWORD
      value: "cloud"
    ports:
      - containerPort: 5984
        hostPort: 30006

...