---
  - name: create vm2 instance
    openstack.cloud.server:
      state: present
      cloud: openstack
      name: team10-VM2-ansible
      image: CC-Ubuntu20.04
      network: CH-819381-net
      availability_zone: nova
      key_name: team10-key
      timeout: 500
      flavor: m1.small
      security_groups:
        - ENABLE_HTTP_HTTPS
        - ENABLE_ICMP
        - ENABLE_K8s
        - ENABLE_KAFKA_COUCHDB
        - ENABLE_KAFKA_COUCH_SSH
        - ENABLE_SSH
        - ENABLE_WIREGUARD
        - ENABLE_ZMQ_APPS
      floating_ips:
        - 129.114.26.148
  - name: launch VM3 instance
    openstack.cloud.server:
      state: present
      cloud: openstack
      name: team10-VM3-ansible
      image: CC-Ubuntu20.04
      network: CH-819381-net
      availability_zone: nova
      key_name: team10-key
      timeout: 500
      flavor: m1.small
      security_groups:
        - ENABLE_HTTP_HTTPS
        - ENABLE_ICMP
        - ENABLE_K8s
        - ENABLE_KAFKA_COUCHDB
        - ENABLE_KAFKA_COUCH_SSH
        - ENABLE_SSH
        - ENABLE_WIREGUARD
        - ENABLE_ZMQ_APPS
      floating_ips:
        - 129.114.27.112
...