---
- name: Zookeeper Service
  shell: "kubectl apply -f Container_Deployments/service/zookeeper-service.yaml"

  
- name: Kafka Service
  shell: "kubectl apply -f Container_Deployments/service/kafka-service.yaml"

- name: Zookeeper Deployment
  shell: "kubectl apply -f Container_Deployments/deployment/zookeeper-deployment.yaml"
- name: Pause for 15 seconds to build container
  pause:
    seconds: 15
- name: Kafka Deployment
  shell: "kubectl apply -f Container_Deployments/deployment/kafka-deployment.yaml"
- name: Pause for 15 seconds to build container
  pause:
    seconds: 15
- name: Consumer Job
  shell: "kubectl apply -f Container_Deployments/consumer-job/consumer-deployment.yaml"
...