---
- name: Copy Service repo
  ansible.builtin.copy:
    src: /vagrant/service/
    dest: /
    remote_src: yes
- name: Copy Deployment repo
  ansible.builtin.copy:
    src: /vagrant/deployment/
    dest: /
    remote_src: yes
- name: Copy Job repo
  ansible.builtin.copy:
    src: /vagrant/consumer-job/
    dest: /
    remote_src: yes

- name: Zookeeper Service
  shell: "kubectl apply -f service/zookeeper-service.yaml"
- name: Kafka Service
  shell: "kubectl apply -f service/kafka-service.yaml"
- name: Couchdb Service
  shell: "kubectl apply -f service/couchdb-service.yaml"

- name: Zookeeper Deployment
  shell: "kubectl apply -f deployment/zookeeper-deployment.yaml"
- name: Pause for 15 seconds to build container
  pause:
    seconds: 15
- name: Kafka Deployment
  shell: "kubectl apply -f deployment/kafka-deployment.yaml"
- name: Pause for 15 seconds to build container
  pause:
    seconds: 15
- name: Couchdb Deployment
  shell: "kubectl apply -f deployment/couchdb-deployment.yaml"

- name: Consumer Job
  shell: "kubectl apply -f consumer-job/consumer-deployment.yaml"
...