---
- name: Install Docker
  apt:
    name: docker.io
    state: latest
    update_cache: yes

- name: Docker mod (from slides)
  replace:
    path: /lib/systemd/system/docker.service
    regexp: 'ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock'
    replace: 'ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --exec-opt native.cgroupdriver=systemd'

- name: Restart service docker and daemon-reload
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: docker

# kubernetes install
- name: Installing Kubernetes Cluster Packages.
  apt:
    pkg:
      - kubeadm
      - kubectl
      - kubelet
      - kubernetes-cni
    state: latest
    update_cache: true

- name: Disable K8 swap
  command: swapoff -a

- name: Set Aliases
  replace:
    path: /etc/hosts
    regexp: 'ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock'
    replace: 'ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --exec-opt native.cgroupdriver=systemd'

- name: Docker Modification
  shell: "systemctl daemon-reload"

- name: Docker Modification
  shell: "systemctl restart docker"

- name: Check Docker Status
  shell: "systemctl status docker"
...