---
- name: Remove Older Versions of Docker
  shell: "apt-get remove docker  docker-engine  docker.io containerdrunc"

- name: Apt Update
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  
- name: Apt-Get repositories
  shell: "apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common"

- name: Curl
  shell: "curl –fsSLhttps://download.docker.com/linux/ubuntu/gpg| sudoapt-key add -"

- name: Add key
  shell: "apt-key fingerprint 0EBFCD88"

- name: Apt Repository
  shell: "add-apt-repository “deb [arch=amd64] https://download.docker.com/linux/ubuntu$(lsb_release-cs) stable”"

- name: Apt Update
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Install Docker
  shell: "apt-get install docker-cedocker-ce-cli  containerd.io"

- name: Dependancies Download
  apt:
    name: python3-dev
- name: Dependancies Download
  apt:
    name: libffi-dev
- name: Dependancies Download
  apt:
    name: libssl-dev
- name: Dependancies Download
  apt:
    name: gcc
- name: Dependancies Download
  apt:
    name: libc-dev
- name: Dependancies Download
  apt:
    name: make

- name: Docker Compose curl
  shell: "curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose"

- name: Change Docker Compose file permissions
  shell: "chmod +x /usr/local/bin/docker-compose"

- name: Dependancies
  shell: "apt install -y apt-transport-https ca-certificates curl"
- name: Curl K8
  shell: "curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg"
- name: Echo
  shell: 'echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg]  https://apt.kubernetes.io/ kubernetes-xenialmain" | sudotee -a /etc/apt/sources.list.d/kubernetes.list'
- name: Apt update
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
- name: Install K8
  shell: "apt install kubeadm kubelet kubectl kubernetes-cni"

- name: Docker Modification
  shell: "systemctl daemon-reload"

- name: Docker Modification
  shell: "systemctlrestart docker"

...