---
- name: init
  shell: "sudo kubeadm init --node-name kubemaster --pod-network-cidr=10.244.0.0/16"

- name: mkdir
  shell: "mkdir -p $HOME/.kube"

- name: config
  shell: "sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"

- name: ownership
  shell: "sudo chown $(id -u):$(id -g) $HOME/.kube/config"

- name: Flannel
  become: no
  shell: "sudo kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"

- name: print join cmd
  become: no
  shell: "sudo kubeadm token create --print-join-command + --node-name kubeworker2"
  register: join_cmd
...