---
- name: Run zookeeper and kafka servers on VM2
  shell: 'bin/zookeeper-server-start.sh config/zookeeper.properties'
  async: 3600 #run for 1hour
  poll: 0

- name: Start kafka on VM2
  shell: 'bin/kafka-server-start.sh config/server.properties'
  async: 3600 #Run for 1hour
  poll: 0
...