---
- name: Allow Kafka
  shell: "sudo ufw allow proto tcp from any to any port 9092"

- name: Allow Zookeeper
  shell: "sudo ufw allow proto tcp from any to any port 2181"

- name: Allow CouchDB
  shell: "sudo ufw allow proto tcp from any to any port 5984"

- name: Allow Docker
  shell: "sudo ufw allow proto tcp from any to any port 5000"

- name: Allow K8_1
  shell: "sudo ufw allow proto tcp from any to any port 10255"

- name: Allow K8_2
  shell: "sudo ufw allow proto tcp from any to any port 10256"
...
