---
apiVersion: apps/v1
# @Andy: I just swapped these two lines making apiVersion the first line
kind: Deployment
metadata:
  name: zookeeper-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoo
  template:
    metadata:
      labels:
        app: zoo
    spec:
      nodeSelector: # this shows how you force k8s to schedule the pod on a specified node
        kubernetes.io/hostname: kubemaster
      containers:
        # @Andy: Changed the name of the container from zoo to the one below
        # because I am not sure if there will be a conflict between the "zoo" pod name
        # and container name
        - name: zoo-container
          image: digitalwonderland/zookeeper
          ports:
            - containerPort: 2181
...