---
- name: Allow Kafka
  shell: "sudo ufw allow proto tcp from any to any port 9092"

- name: Allow Zookeeper
  shell: "sudo ufw allow proto tcp from any to any port 2181"

- name: Allow CouchDB
  shell: "sudo ufw allow proto tcp from any to any port 5984"

- name: Allow Docker
  shell: "sudo ufw allow proto tcp from any to any port 5000"

- name: Allow K8_1
  shell: "sudo ufw allow proto tcp from any to any port 10255"

- name: Allow K8_2
  shell: "sudo ufw allow proto tcp from any to any port 10256"

- name: Allow K8 dependencies
  shell: "sudo ufw limit 2379:2380/tcp"

- name: Allow K8 dependencies
  shell: "sudo ufw limit 6443/tcp"

- name: Allow K8 dependencies
  shell: "sudo ufw limit 10250:10252/tcp"

- name: Allow K8 dependencies
  shell: "sudo ufw limit 8285/udp"

- name: Allow K8 dependencies
  shell: "sudo ufw limit 8472/udp"

- name: Allow K8 dependencies
  shell: "sudo ufw limit 30000:30004/tcp"

- name: Allow K8 dependencies
  shell: "sudo ufw limit 30005/tcp"

- name: Allow K8 dependencies
  shell: "sudo ufw limit 30006/tcp"

- name: Allow spark dependencies
  shell: "sudo ufw limit 7077/tcp"

- name: Allow spark dependencies
  shell: "sudo ufw limit 8080"

- name: allow spark dep
  shell: "sudo ufw limit 30008"

- name: spark dep
  shell: "sudo aufw limit 7076"

- name: spark dep
  shell: "sudo aufw limit 7078"

- name: spark dep
  shell: "sudo aufw limit 8081"

- name: spark dep
  shell: "sudo aufw limit 7079"
...
