---
apiVersion: v1
kind: Service
metadata: 
  name: kafka-service
  labels:
    name: kafka1
spec:
  type: NodePort
  selector:
    app: kafka1
    id: "0"
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30000

---
apiVersion: v1
kind: Service
metadata: 
  name: kafka-service
  labels:
    name: kafka2
spec:
  selector:
    app: kafka2
    id: "1"
  type: NodePort
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30001

---
apiVersion: v1
kind: Service
metadata: 
  name: kafka-service
  labels:
    name: kafka3
spec:
  selector:
    app: kafka3
    id: "2"
  type: NodePort
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30002

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka4
spec:
  selector:
    app: kafka4
    id: "3"
  type: NodePort
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30003

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka5
spec:
  selector:
    app: kafka5
    id: "4"
  type: NodePort
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30004
...