---
apiVersion: v1
kind: Service
metadata: 
  name: kafka1
  namespace: kafka-cluster
  labels:
    app: kafka-broker-1
spec:
  selector:
    app: kafka-broker-1
  type: NodePort
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30000

---
apiVersion: v1
kind: Service
metadata:
  name: kafka2
  namespace: kafka-cluster
  labels:
    app: kafka-broker-2
spec:
  selector:
    app: kafka-broker-2
  type: NodePort
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30001

---
apiVersion: v1
kind: Service
metadata:
  name: kafka3
  namespace: kafka-cluster
  labels:
    app: kafka-broker-3
spec:
  selector:
    app: kafka-broker-3
  type: NodePort
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30002

---
apiVersion: v1
kind: Service
metadata:
  name: kafka4
  namespace: kafka-cluster
  labels:
    app: kafka-broker-4
spec:
  selector:
    app: kafka-broker-4
  type: NodePort
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30003

---
apiVersion: v1
kind: Service
metadata:
  name: kafka5
  namespace: kafka-cluster
  labels:
    app: kafka-broker-5
spec:
  selector:
    app: kafka-broker-5
  type: NodePort
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30004
...