---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: couchdb-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: couch-server-app
  minReadySeconds: 5

  template:
    metadata: 
      labels:
        app: couch-server-app
    spec:
      containers: 
      - name: couchdb
        image: couchdb:latest
        env:
        - name: COUCHDB_USER
          value: admin
        - name: COUCHDB_PASSWORD
          value: admin
        ports:
        - containerPort: 5984

