---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: couchdb-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: couch-server-app
  minReadySeconds: 5

  template:
    metadata: 
      labels:
        app: couch-server-app
    spec:
      containers: 
      - name: couchdb
        image: couchdb:latest
        env:
        - name: COUCHDB_USER
          value: admin
        - name: COUCHDB_PASSWORD
          value: admin
        ports:
        - containerPort: 5984

---

apiVersion: v1
kind: Service
metadata: 
  name: couch-server-app
spec:
  type: NodePort
  selector: 
    app: couch-server-app
  ports:
    - protocal: TCP
      port: 5984
      nodePort: 30006

...

apiVersion: v1
kind: Pod
metadata: 
  name: couch-service
spec:
  containers: 
  - name: couch-service
    image: couchdb:latest
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 5984
        hostPort: 30006 