---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kafka-broker0
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: kafka1
      id: "0"
  template:
    metadata: 
      labels:
        app: kafka1
        id: "0"
    spec:
      hostname: kafka03-host
        nodeSelector: # this shows how you force k8s to schedule the pod on a specified node
          kubernetes.io/hostname: kubemaster
      containers: 
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 5984
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo:2181
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: ALLOW_PLAINTEXT_LISTINER
          value: "yes"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: 129.114.26.148:9092

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kafka-broker0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka2
      id: "1"
  template:
    metadata: 
      labels:
        app: kafka2
        id: "1"
    spec:
      hostname: kafka03-host
        nodeSelector: # this shows how you force k8s to schedule the pod on a specified node
          kubernetes.io/hostname: kubemaster
      containers: 
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 5984
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo:2181
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: ALLOW_PLAINTEXT_LISTINER
          value: "yes"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: 129.114.26.148:9092

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kafka-broker0
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: kafka3
      id: "2"
  template:
    metadata: 
      labels:
        app: kafka3
        id: "2"
    spec:
      hostname: kafka03-host
        nodeSelector: # this shows how you force k8s to schedule the pod on a specified node
          kubernetes.io/hostname: kubemaster
      containers: 
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 5984
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo:2181
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: ALLOW_PLAINTEXT_LISTINER
          value: "yes"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: 129.114.26.148:9092
        - name: KAFKA_CREATE_TOPICS
          value: "utilizations:1:1"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka4
      id: "3"
  template:
    metadata:
      labels:
        app: kafka4
        id: "3"
    spec:
      hostname: kafka45-host
        nodeSelector: # this shows how you force k8s to schedule the pod on a specified node
          kubernetes.io/hostname: kubeworker2
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 5984
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo:2181
            - name: KAFKA_BROKER_ID
              value: "3"
            - name: ALLOW_PLAINTEXT_LISTINER
              value: "yes"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: 129.114.26.148:9092

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka5
      id: "4"
  template:
    metadata:
      labels:
        app: kafka5
        id: "4"
    spec:
      hostname: kafka45-host
        nodeSelector: # this shows how you force k8s to schedule the pod on a specified node
          kubernetes.io/hostname: kubeworker2
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 5984
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo:2181
            - name: KAFKA_BROKER_ID
              value: "4"
            - name: ALLOW_PLAINTEXT_LISTINER
              value: "yes"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: 129.114.26.148:9092
...