---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper-deploy
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: zoo
  template:
    metadata:
      labels:
        app: zoo
    spec:
      containers:
      - name: zoo
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181