---
apiVersion: v1
kind: Service
metadata:
  name: kb0-svc
spec:
  type: NodePort
  selector:
    app: kb0App
  ports:
  - name: kb0-port
    protocol: TCP
    port: 9092
    targetPort: 9092
    nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: kb1-svc
spec:
  type: NodePort
  selector:
    app: kb1App
  ports:
  - name: kb0-port
    protocol: TCP
    port: 9092
    targetPort: 9092
    nodePort: 30001
...