---
apiVersion: v1
kind: Service
metadata:
  name: zk-svc
spec:
  type: NodePort
  selector:
    app: zkApp
  ports:
  - name: zk-port
    protocol: TCP
    port: 2181
    targetPort: 2181
    nodePort: 30005
...