# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Every Vagrant development environment requires a box.
  config.vm.box = "ubuntu/focal64"   # Ubuntu 18.04 (use focal64 for 20.04)

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder ".", "/vagrant"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "2048"
  end

  # The shell provisioner can also accept a script that will be executed in
  # the guest in user mode (by default). See the bootstrap.sh script
  # where we create the above directories and they all will execute
  # as the user "vagrant" by default 
  config.vm.provision "shell", path: "bootstrap.sh"

  # let's copy our pem file to the vagrant created guest. Change the file name
  # as appropriate in your case and also the file path based on where on your
  # host you have stored this file.
  config.vm.provision "file", source: "C:/Users/awggs/.ssh/team10-key.pem", destination: "/home/vagrant/.ssh/"
  config.vm.provision "file", source: "C:/Users/awggs/.ssh/team10-publickey", destination: "/home/vagrant/.ssh/"
  config.vm.provision "file", source: "./install_couchdb.sh", destination: "/home/vagrant/"
  config.vm.provision "file", source: "./consumer.py", destination: "/home/vagrant/"
  config.vm.provision "file", source: "./playbook_demo_master.yml", destination: "/home/vagrant/"
  config.vm.provision "file", source: "./tasks", destination: "/home/vagrant/"

  # make sure the permissions on the  pem file are not too open.
  # Note, here I show you using inline and privileged: false so the inline
  # action actually happens as the user vagrant.
  # Moreover, we also show a diff approach to put the inline code in
  # a block, and then use the block name. 
  # Change file name as appropriate. Replace this with your pem file.
  $script = <<-SCRIPT
     chmod go-rwx /home/vagrant/.ssh/team10-key.pem
  SCRIPT
  config.vm.provision "shell", inline: $script, privileged: false

  # let's also copy our ansible.cfg, MyInventory and cloud.yaml file
  config.vm.provision "file", source: "./.ansible.cfg", destination: "~/.ansible.cfg"
  config.vm.provision "file", source: "./MyInventory", destination: "~/.ansible/MyInventory"
  config.vm.provision "file", source: "C:/Users/awggs/.config/openstack/clouds.yaml", destination: "~/.config/openstack/clouds.yaml"
  # copy an AWS version
  # config.vm.provision ...

  # other installations
#   config.vm.provision "shell", inline: <<-SHELL
#     sudo apt-get update
#     sudo apt install pip
#     sudo ansible-galaxy collection install openstack.cloud
#     sudo python3 -m pip install --upgrade openstacksdk
#   SHELL

  # We now use the Ansible provisioner
  #
  # in the following, install= true will install ansible in the
  # created or provisioned guest vm. Once ansible is installed, any
  # additional configuration we plan to do will be taken from the
  # supplied playbook. Moreover, we can also tell ansible which
  # Inventory file it should use. This inventory file will appear in the
  # /vagrant directory (which is the same directory on your host that has
  # the vagrantfile but is mounted as /vagrant in the guest machine)
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook_demo_master.yml"
    ansible.verbose = true
    ansible.install = true  # installs ansible (and hence python on VM)
    ansible.limit = "all"
    ansible.inventory_path = "./MyInventory"  # inventory file
  end
end
