---
- name: Importing couchdb key
  apt_key:
    url: https://couchdb.apache.org/repo/keys.asc
    keyring: /usr/share/keyrings/couchdb-archive-keyring.gpg
- name: Adding couchdb repo
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/couchdb-archive-keyring.gpg] https://apache.jfrog.io/artifactory/couchdb-deb/ focal main
    update_cache: yes
- name: Update Cache
  apt:
    update_cache: yes
- name: Install couchdb
  apt: 
    name: couchdb
    state: present
- name: Copy local.ini file to create admin user
  copy: 
    src: /vagrant/local.ini
    dest: /opt/couchdb/etc/local.ini
- name: Change Local.ini permisions
  ansible.builtin.command: chmod 640 /opt/couchdb/etc/local.ini
- name: restart couchdb service
  systemd:
    name: couchdb
    state: restarted
    daemon_reload: yes
...
