---
- hosts: MyChameleonVMs
	remote_user:  cc   # change the user to whatever is the user on the cloud VM
	collections:   # this is new starting with Ansible 2.9 (akin to importing package)
		- openstack.cloud
	become: yes
	tasks: 
		- name: Performing update
			apt:
				update_cache: yes
				force_apt_get: yes
				cache_valid_time: 3600

		- name: Upgrade all packages on servers
			apt:
				upgrade: dist 
				force_apt_get: yes

		- name: Install java package
			apt:
				name: openjdk-11-jre-headless
				state: latest

		- name: Remove Kafka dir
			shell: "rm -rf kafka"

		- name: Create Kafka dir
			shell: "mkdir kafka"

		- name: Download kafka
			shell: "curl \"https://dlcdn.apache.org/kafka/2.8.1/kafka_2.13-2.8.1.tgz\" -o ./kafka/kafka.tgz"

		- name: Extracting Kafka
			shell: "tar -xvzf kafka/kafka.tgz --strip 1"
...
