---
- hosts: MyChameleonVMs
  remote_user: cc
  collections:
    - openstack.cloud
  become: yes
  tasks:
    - name: Kafka Download
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 5000
    - name: upgrade
      apt:
        upgrade: dist
        force_apt_get: yes
    - name: install java
      apt:
        name: openjdk-11-jre-headless
        state: latest
    - name: remove kafka dir
      shell: "rm -rf kafka"

    - name: create kafka dir
      shell: "mkdir kafka"

    - name: download kafka
      shell: "curl \"https://dlcdn.apache.org/kafka/2.8.1/kafka_2.13-2.8.1.tgz\" -o ./kafka/kafka.tgz"

    - name: extract kafka
      shell: "tar -xvzf kafka/kafka.tgz --strip 1"
...
