---
- name: Change listeners
  replace:
    dest: config/server.properties
    regexp: '#listeners=PLAINTEXT://:9092'
    replace: 'listeners=PLAINTEXT://10.212.96.53:9092'

- name: Change advertised listeners
  replace:
    dest: config/server.properties
    regexp: '#advertised.listeners=PLAINTEXT://your.host.name:9092'
    replace: 'advertised.listeners=PLAINTEXT://129.114.26.148:9092'

- name: Uncomment Security protocal
  replace:
    dest: config/server.properties
    regexp: '#listener.security.protocol.map=PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL'
    replace: 'listener.security.protocol.map=PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL'
...
