---
- name: Set UFW rules for both VMS
  hosts: MyChameleonVMs
  remote_user: cc
  become: yes
  tasks:
    - name: Allow Kafka
      community.general.ufw:
        rule: limit
        port: 9092

    - name: Allow Zookeeper
      community.general.ufw:
        rule: limit
        port: 2181
    
    - name: Allow CouchDB
      community.general.ufw:
        rule: limit
        port: 5984
...
