---
- name: Set UFW rules for both VMS

  hosts: MyChameleonVMs
  remote_user: cc
  collections:   # this is new starting with Ansible 2.9 (akin to importing package)
    - openstack.cloud
  become: yes
  tasks:
    - name: Allow Kafka
      shell:  "sudo ufw allow proto tcp from any to any port 9092"

    - name: Allow Zookeeper
      shell:  "sudo ufw allow proto tcp from any to any port 2181"
    
    - name: Allow CouchDB
      shell:  "sudo ufw allow proto tcp from any to any port 5984"
...
