---
#
# Author: Matt Steele, Austin Groeneveld
#
- name: Create a new instance VM1 on the openstack cloud
  hosts: MyLocalVMs
  remote_user: vagrant

  tasks:
    - name: create security group
      os_security_group:
        cloud: "CH-819381"
        state: present
        name: security-group
        description: Security group for our instance

    - name: create security group rule for ping
      os_security_group_rule:
        cloud: "CH-819381"
        security_group: security-group
        protocol: icmp
        remote_ip_prefix: 0.0.0.0/0

    - name: create security group rule for kafka
      openstack.cloud.security_group_rule:
        cloud: "CH-819381"
        security_group: security-group
        protocol: tcp
        port: 80
        remote_ip_prefix: 0.0.0.0/0

    - name: create security group rule for SSH
      os_security_group_rule:
        cloud: "CH-819381"
        security_group: security-group
        protocol: tcp
        port: 22
        remote_ip_prefix: 0.0.0.0/0

    - name: create instance
      os_server:
        state: present
        cloud: "CH-819381"
        name: VM1
        image: ubuntu-14.04
        key_name: team10-publickey
        timeout: 200
        flavor: m1.small
        floating_ips:
          - 129.114.26.148
        security_groups: security-group
      register:
        VM1

...